#ifndef __DEFCONFIG_H__
#define __DEFCONFIG_H__ 

#ifndef MAX_SUPPORTED_KEY_VAL
#define MAX_SUPPORTED_KEY_VAL 0x65 
#endif 


// Available: BOOT_DESCRIPTOR, ID_DESCRIPTORS, COMPOSITE, NKRO
#ifndef HID_DESCRIPTOR_TYPE
#define HID_DESCRIPTOR_TYPE BOOT_DESCRIPTORS 
#endif

#endif // __DEFCONFIG_H__
