#ifndef __DEFKEYMAPS_H__
#define __DEFKEYMAPS_H__ 

#define DEFAULT_KEYMAP keymap_init0

const struct keymap keymap_init0 =
{
		.grid =
				KEYMAP(	\ 
					ESCAPE, 1_AND_EXCLAMATION, 2_AND_AT, 3_AND_HASHMARK, 4_AND_DOLLAR, 5_AND_PERCENTAGE, 6_AND_CARET, 7_AND_AMPERSAND, 8_AND_ASTERISK, 9_AND_OPENING_PARENTHESIS, 0_AND_CLOSING_PARENTHESIS, MINUS_AND_UNDERSCORE, EQUAL_AND_PLUS, BACKSPACE, PAGE_UP, \
						TAB, Q, W, E, R, T, Y, U, I, O, P, OPENING_BRACKET_AND_OPENING_BRACE, CLOSING_BRACKET_AND_CLOSING_BRACE, BACKSLASH_AND_PIPE, PAGE_DOWN, \
						CAPS_LOCK, A, S, D, F, G, H, J, K, L, SEMICOLON_AND_COLON, APOSTROPHE_AND_QUOTE, RESERVED, ENTER, HOME, \
						LEFT_SHIFT, RESERVED, Z, X, C, V, B, N, M, COMMA_AND_LESS_THAN_SIGN, DOT_AND_GREATER_THAN_SIGN, SLASH_AND_QUESTION_MARK, RIGHT_SHIFT, UP_ARROW, END, \
						RIGHT_CONTROL, RIGHT_GUI, RIGHT_ALT, RESERVED, RESERVED, RESERVED, SPACE, RESERVED, RESERVED, RESERVED, LAYER_FUNCTION, MACRO_SET_FUNCTION, LEFT_ARROW, DOWN_ARROW, RIGHT_ARROW),
        .type = keymap_layer,
	    .modifier = 0x00,
	    .name = "Initial_layer"
};


#endif // __DEFKEYMAPS_H__
