#ifndef __KEYMAP_CONFIG_H__
#define __KEYMAP_CONFIG_H__ 

#define HID_KEYBOARD_SC_LAYER_FUNCTION 0xFF 
#define HID_KEYBOARD_SC_MACRO_SET_FUNCTION 0xFE 
#define HID_KEYBOARD_SC_MACRO_RUN_FUNCTION 0xFC 
#define HID_KEYBOARD_SC_CLI_FUNCTION 0xFB


#endif // __KEYMAP_CONFIG_H__
