/*
 * keymap_defaults.h
 *
 *  Created on: 23 Jan 2019
 *      Author: alxhoff
 */

#ifndef KEYMAP_DEFAULTS_H_
#define KEYMAP_DEFAULTS_H_

#include "HIDClassCommon.h"
#include "keymap.h"

#define KEYMAP_DEFAULT_ID 0
#define KEYMAP_FUNC_ID 1

const keymap_layer_t keymap_init0 = { .grid =
		KEYMAP(ESCAPE, 1_AND_EXCLAMATION, 2_AND_AT, 3_AND_HASHMARK,
				4_AND_DOLLAR, 5_AND_PERCENTAGE, 6_AND_CARET, 7_AND_AMPERSAND,
				8_AND_ASTERISK, 9_AND_OPENING_PARENTHESIS,
				0_AND_CLOSING_PARENTHESIS, MINUS_AND_UNDERSCORE, EQUAL_AND_PLUS,
				BACKSPACE, PAGE_UP, KEYPAD_TAB, Q, W, E, R, T, Y, U, I, O, P,
				OPENING_BRACKET_AND_OPENING_BRACE,
				CLOSING_BRACKET_AND_CLOSING_BRACE, BACKSLASH_AND_PIPE,
				PAGE_DOWN, LOCKING_CAPS_LOCK, A, S, D, F, G, H, J, K, L,
				SEMICOLON_AND_COLON, APOSTROPHE_AND_QUOTE, NO, ENTER, HOME,
				LEFT_SHIFT, NO, Z, X, C, V, B, N, M, COMMA_AND_LESS_THAN_SIGN,
				DOT_AND_GREATER_THAN_SIGN, SLASH_AND_QUESTION_MARK, RIGHT_SHIFT,
				UP_ARROW, END, RIGHT_CONTROL, RIGHT_GUI, RIGHT_ALT, NO, NO, NO,
				SPACE, NO, NO, NO, LAYER_FUNCTION, MACRO_SET_FUNCTION,
				LEFT_ARROW, DOWN_ARROW, RIGHT_ARROW), .mod_key_code = 0x66,
		.name = "default", .ID = KEYMAP_DEFAULT_ID };

const keymap_layer_t keymap_init1 = { .grid =
		KEYMAP(ESCAPE, 1_AND_EXCLAMATION, 2_AND_AT, 3_AND_HASHMARK,
				4_AND_DOLLAR, 5_AND_PERCENTAGE, 6_AND_CARET, 7_AND_AMPERSAND,
				8_AND_ASTERISK, 9_AND_OPENING_PARENTHESIS,
				0_AND_CLOSING_PARENTHESIS, MINUS_AND_UNDERSCORE, EQUAL_AND_PLUS,
				BACKSPACE, PAGE_UP, KEYPAD_TAB, Q, W, E, R, T, Y, U, I, O, P,
				OPENING_BRACKET_AND_OPENING_BRACE,
				CLOSING_BRACKET_AND_CLOSING_BRACE, BACKSLASH_AND_PIPE,
				PAGE_DOWN, LOCKING_CAPS_LOCK, A, S, D, F, G, H, J, K, L,
				SEMICOLON_AND_COLON, APOSTROPHE_AND_QUOTE, NO, ENTER, HOME,
				LEFT_SHIFT, NO, Z, X, C, V, B, N, M, COMMA_AND_LESS_THAN_SIGN,
				DOT_AND_GREATER_THAN_SIGN, SLASH_AND_QUESTION_MARK, RIGHT_SHIFT,
				UP_ARROW, END, RIGHT_CONTROL, RIGHT_GUI, RIGHT_ALT, NO, NO, NO,
				SPACE, NO, NO, NO, LAYER_FUNCTION, MACRO_SET_FUNCTION,
				LEFT_ARROW, DOWN_ARROW, RIGHT_ARROW), .mod_key_code =
		HID_KEYBOARD_SC_Q, .name = "function", .ID =
KEYMAP_FUNC_ID };

unsigned char no_default_keymap_layers = 2;
keymap_layer_t default_keymap_layers[] = { keymap_init0, keymap_init1 };

#endif /* KEYMAP_DEFAULTS_H_ */
