/*
 * keymap.h
 *
 *  Created on: Aug 16, 2017
 *      Author: alxhoff
 */

#ifndef KEYMAP_H_
#define KEYMAP_H_

#include "HIDClassCommon.h"
#include "config.h"


#define K_ESC			HID_KEYBOARD_SC_ESCAPE
#define K_1				HID_KEYBOARD_SC_1_AND_EXCLAMATION
#define K_2				HID_KEYBOARD_SC_2_AND_AT
#define K_3				HID_KEYBOARD_SC_3_AND_HASHMARK
#define K_4				HID_KEYBOARD_SC_4_AND_DOLLAR
#define K_5				HID_KEYBOARD_SC_5_AND_PERCENTAGE
#define K_6				HID_KEYBOARD_SC_6_AND_CARET
#define K_7				HID_KEYBOARD_SC_7_AND_AMPERSAND
#define K_8				HID_KEYBOARD_SC_8_AND_ASTERISK
#define K_9				HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS
#define K_0				HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS
#define K_MINS			HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE
#define K_EQUAL			HID_KEYBOARD_SC_EQUAL_AND_PLUS
#define K_BSPC			HID_KEYBOARD_SC_BACKSPACE
#define K_DEL			HID_KEYBOARD_SC_DELETE
#define K_TAB			HID_KEYBOARD_SC_TAB
#define K_Q				HID_KEYBOARD_SC_Q
#define K_W				HID_KEYBOARD_SC_W
#define K_E				HID_KEYBOARD_SC_E
#define K_R				HID_KEYBOARD_SC_R
#define K_T				HID_KEYBOARD_SC_T
#define K_Y				HID_KEYBOARD_SC_Y
#define K_U				HID_KEYBOARD_SC_U
#define K_I				HID_KEYBOARD_SC_I
#define K_O				HID_KEYBOARD_SC_O
#define K_P				HID_KEYBOARD_SC_P
#define K_LBRC			HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE
#define K_RBRC			HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE
#define K_ENTER			HID_KEYBOARD_SC_ENTER
#define K_CAPS			HID_KEYBOARD_SC_LOCKING_CAPS_LOCK
#define K_A				HID_KEYBOARD_SC_A
#define K_S				HID_KEYBOARD_SC_S
#define K_D				HID_KEYBOARD_SC_D
#define K_F				HID_KEYBOARD_SC_F
#define K_G				HID_KEYBOARD_SC_G
#define K_H				HID_KEYBOARD_SC_H
#define K_J				HID_KEYBOARD_SC_J
#define K_K				HID_KEYBOARD_SC_K
#define K_L				HID_KEYBOARD_SC_L
#define K_COLON			HID_KEYBOARD_SC_SEMICOLON_AND_COLON
#define K_QUOTE			HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE
#define K_BSLASH		HID_KEYBOARD_SC_BACKSLASH_AND_PIPE
#define K_LSHIFT		HID_KEYBOARD_SC_LEFT_SHIFT
#define K_Z				HID_KEYBOARD_SC_Z
#define K_X				HID_KEYBOARD_SC_X
#define K_C				HID_KEYBOARD_SC_C
#define K_V				HID_KEYBOARD_SC_V
#define K_B				HID_KEYBOARD_SC_B
#define K_N				HID_KEYBOARD_SC_N
#define K_M				HID_KEYBOARD_SC_M
#define K_COMMA			HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN
#define K_DOT			HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN
#define K_SLASH			HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK
#define K_RSHIFT		HID_KEYBOARD_SC_RIGHT_SHIFT
#define K_LCTRL			HID_KEYBOARD_SC_LEFT_CONTROL
#define K_LGUI			HID_KEYBOARD_SC_LEFT_GUI
#define K_LALT			HID_KEYBOARD_SC_LEFT_ALT
#define K_SPACE			HID_KEYBOARD_SC_SPACE
#define K_RALT			HID_KEYBOARD_SC_RIGHT_ALT
#define K_RGUI			HID_KEYBOARD_SC_RIGHT_GUI
#define K_FN
#define K_RCRTL			HID_KEYBOARD_SC_RIGHT_CONTROL
#define K_NO			0
#define K_PGUP			HID_KEYBOARD_SC_PAGE_UP
#define K_PGDWN			HID_KEYBOARD_SC_PAGE_DOWN
#define K_END			HID_KEYBOARD_SC_END
#define K_HOME			HID_KEYBOARD_SC_HOME
#define K_TAB			HID_KEYBOARD_SC_KEYPAD_TAB

//ARROWS
#define K_LEFT			HID_KEYBOARD_SC_LEFT_ARROW
#define K_RIGHT			HID_KEYBOARD_SC_RIGHT_ARROW
#define K_UP			HID_KEYBOARD_SC_UP_ARROW
#define K_DOWN			HID_KEYBOARD_SC_DOWN_ARROW

#define K_LAYER			HID_KEYBOARD_SC_LAYER_FUNCTION
#define K_MACRO_R		HID_KEYBOARD_SC_MACRO_RUN_FUNCTION
#define K_MACRO_S		HID_KEYBOARD_SC_MACRO_SET_FUNCTION
#define K_CLI			HID_KEYBOARD_SC_CLI_FUNCTION

//MEDIA
#define K_PLAY			HID_KEYBOARD_SC_MEDIA_PLAY

//NUMPAD
#define K_NUM1			HID_KEYBOARD_SC_KEYPAD_1_AND_END
#define K_NUM2			HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW
#define K_NUM3			HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN
#define K_NUM4			HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW
#define K_NUM5			HID_KEYBOARD_SC_KEYPAD_5
#define K_NUM6			HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW
#define K_NUM7			HID_KEYBOARD_SC_KEYPAD_7_AND_HOME
#define K_NUM8			HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW
#define K_NUM9			HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP
#define K_NUM0			HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT

//prototypes

void keymap_set_key(unsigned char row,
		unsigned char col, unsigned char val);
unsigned char keymap_get_key(unsigned char row,
		unsigned char col);
unsigned char keymap_get_key_sk(scaned_key_t sk);
void keymap_set_name(char* name);
char *keymap_get_name(void);
void keymap_set_mod_key_code(unsigned char code);
unsigned char keymap_get_mod_key_code(void);
unsigned char keymap_get_ID(void);



#endif /* KEYMAP_H_ */
